# Generated by Django 2.1.2 on 2019-07-08 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='estado',
            field=models.CharField(choices=[('Reportado', 'Reportado'), ('En proceso', 'En proceso'), ('Resuelto', 'Resuelto'), ('Descartado', 'Descartado')], default=('Reportado', 'Reportado'), max_length=30),
        ),
        migrations.AddField(
            model_name='report',
            name='fechacreacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
