# Generated by Django 2.1.2 on 2019-07-08 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190708_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='estado',
            field=models.CharField(choices=[('0', 'Reportado'), ('1', 'En proceso'), ('2', 'Resuelto'), ('3', 'Descartado')], default=('0', 'Reportado'), max_length=1),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
