# Generated by Django 2.1.2 on 2019-07-09 19:48

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20190708_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='geom',
            field=djgeojson.fields.PointField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='estado',
            field=models.CharField(choices=[('0', 'Reportado'), ('1', 'En proceso'), ('2', 'Resuelto'), ('3', 'Descartado')], default='0', max_length=1),
        ),
    ]
