# Generated by Django 2.1.2 on 2019-07-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20190709_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='direccion',
        ),
    ]
